/**
 * H3 Variations for "Free Government Phone" Keyword
 * 200+ unique H3s for city/state pages
 * All natural language - mentions keyword naturally
 */

import { selectVariation } from '../../shared/hash-utils';

// ============================================================================
// CITY PAGE H3 VARIATIONS (100+)
// ============================================================================

const CITY_H3S = [
  "Free Government Phone Service Available",
  "Apply for Free Government Phone Today",
  "Get Your Free Government Phone",
  "Free Government Phone Eligibility",
  "How to Qualify for Free Government Phone",
  "Free Government Phone Benefits",
  "Free Government Phone Providers Nearby",
  "Start Your Free Government Phone Application",
  "Free Government Phone Program Details",
  "Enroll in Free Government Phone Service",
  "Free Government Phone Requirements",
  "About Free Government Phone Programs",
  "Free Government Phone Application Process",
  "Free Government Phone Service Options",
  "Local Free Government Phone Providers",
  "Free Government Phone Coverage",
  "Getting Free Government Phone Benefits",
  "Free Government Phone Sign-Up",
  "Free Government Phone Enrollment",
  "Understanding Free Government Phone",
  "Free Government Phone Program Information",
  "Apply for Free Government Phone Online",
  "Free Government Phone Assistance",
  "Free Government Phone Service Plans",
  "Free Government Phone Federal Programs",
  "Qualify for Free Government Phone",
  "Free Government Phone Application Help",
  "Free Government Phone Service Features",
  "Free Government Phone Benefits Overview",
  "Free Government Phone Provider Options",
  "Available Free Government Phone Programs",
  "Free Government Phone Qualification",
  "Free Government Phone Service Details",
  "Free Government Phone Enrollment Steps",
  "Free Government Phone Program Access",
  "Free Government Phone Application Guide",
  "Local Free Government Phone Services",
  "Free Government Phone Plan Options",
  "Free Government Phone Federal Assistance",
  "Free Government Phone Service Coverage",
  "Free Government Phone Program Eligibility",
  "Free Government Phone Benefits Explained",
  "Free Government Phone Service Providers",
  "Free Government Phone Application Support",
  "Free Government Phone Enrollment Process",
  "Free Government Phone Program Features",
  "Free Government Phone Service Information",
  "Free Government Phone Provider Network",
  "Free Government Phone Benefits Available",
  "Free Government Phone Application Steps",
  "Free Government Phone Program Guide",
  "Free Government Phone Service Access",
  "Free Government Phone Eligibility Criteria",
  "Free Government Phone Provider List",
  "Free Government Phone Program Benefits",
  "Free Government Phone Service Enrollment",
  "Free Government Phone Application Online",
  "Free Government Phone Coverage Areas",
  "Free Government Phone Benefits Program",
  "Free Government Phone Service Application",
  "Free Government Phone Provider Availability",
  "Free Government Phone Program Assistance",
  "Free Government Phone Service Quality",
  "Free Government Phone Enrollment Options",
  "Free Government Phone Application Requirements",
  "Free Government Phone Program Overview",
  "Free Government Phone Service Plans Available",
  "Free Government Phone Provider Selection",
  "Free Government Phone Benefits Details",
  "Free Government Phone Service Support",
  "Free Government Phone Application Process",
  "Free Government Phone Program Enrollment",
  "Free Government Phone Service Benefits",
  "Free Government Phone Provider Information",
  "Free Government Phone Eligibility Requirements",
  "Free Government Phone Program Options",
  "Free Government Phone Service Assistance",
  "Free Government Phone Application Center",
  "Free Government Phone Benefits Access",
  "Free Government Phone Service Qualification",
  "Free Government Phone Provider Coverage",
  "Free Government Phone Program Application",
  "Free Government Phone Service Eligibility",
  "Free Government Phone Enrollment Information",
  "Free Government Phone Application Assistance",
  "Free Government Phone Benefits Enrollment",
  "Free Government Phone Service Programs",
  "Free Government Phone Provider Options Available",
  "Free Government Phone Program Requirements",
  "Free Government Phone Service Available Now",
  "Free Government Phone Application Today",
  "Free Government Phone Benefits Today",
  "Free Government Phone Service Today",
  "Free Government Phone Provider Services",
  "Free Government Phone Program Sign-Up",
  "Free Government Phone Service Access Now",
  "Free Government Phone Enrollment Today",
  "Free Government Phone Application Available",
  "Free Government Phone Benefits Sign-Up",
  "Free Government Phone Service Registration"
];

// ============================================================================
// STATE PAGE H3 VARIATIONS (100+)
// ============================================================================

const STATE_H3S = [
  "Free Government Phone Programs Available",
  "Statewide Free Government Phone Coverage",
  "Free Government Phone Providers",
  "Free Government Phone Eligibility Guidelines",
  "How to Get Free Government Phone",
  "Free Government Phone Application Process",
  "Free Government Phone Benefits",
  "Free Government Phone Service Options",
  "Free Government Phone Program Details",
  "State Free Government Phone Requirements",
  "Free Government Phone Enrollment Information",
  "Free Government Phone Federal Programs",
  "Free Government Phone Service Providers",
  "Free Government Phone Qualification Standards",
  "Free Government Phone Program Benefits",
  "Free Government Phone Application Steps",
  "Free Government Phone Service Coverage",
  "Free Government Phone Provider Network",
  "Free Government Phone Eligibility Rules",
  "Free Government Phone Program Features",
  "Free Government Phone Service Plans",
  "Free Government Phone Application Guide",
  "Free Government Phone Benefits Overview",
  "Free Government Phone Provider Options",
  "Free Government Phone Program Access",
  "Free Government Phone Service Information",
  "Free Government Phone Enrollment Process",
  "Free Government Phone Provider List",
  "Free Government Phone Benefits Available",
  "Free Government Phone Program Assistance",
  "Free Government Phone Service Features",
  "Free Government Phone Application Support",
  "Free Government Phone Coverage Details",
  "Free Government Phone Provider Availability",
  "Free Government Phone Program Eligibility",
  "Free Government Phone Service Quality",
  "Free Government Phone Enrollment Options",
  "Free Government Phone Benefits Program",
  "Free Government Phone Provider Services",
  "Free Government Phone Program Overview",
  "Free Government Phone Service Application",
  "Free Government Phone Eligibility Criteria",
  "Free Government Phone Provider Coverage",
  "Free Government Phone Program Information",
  "Free Government Phone Service Support",
  "Free Government Phone Application Requirements",
  "Free Government Phone Benefits Details",
  "Free Government Phone Provider Network Coverage",
  "Free Government Phone Program Options",
  "Free Government Phone Service Enrollment",
  "Free Government Phone Application Process Guide",
  "Free Government Phone Benefits Explained",
  "Free Government Phone Provider Selection",
  "Free Government Phone Program Requirements",
  "Free Government Phone Service Plans Available",
  "Free Government Phone Enrollment Steps",
  "Free Government Phone Application Center",
  "Free Government Phone Benefits Access",
  "Free Government Phone Provider Information",
  "Free Government Phone Program Enrollment",
  "Free Government Phone Service Qualification",
  "Free Government Phone Eligibility Requirements",
  "Free Government Phone Application Assistance",
  "Free Government Phone Benefits Enrollment",
  "Free Government Phone Provider Options Available",
  "Free Government Phone Program Sign-Up",
  "Free Government Phone Service Assistance",
  "Free Government Phone Coverage Areas",
  "Free Government Phone Application Today",
  "Free Government Phone Benefits Today",
  "Free Government Phone Provider Services Available",
  "Free Government Phone Program Application",
  "Free Government Phone Service Eligibility",
  "Free Government Phone Enrollment Information",
  "Free Government Phone Application Available",
  "Free Government Phone Benefits Sign-Up",
  "Free Government Phone Provider Network Details",
  "Free Government Phone Program Features Available",
  "Free Government Phone Service Access",
  "Free Government Phone Eligibility Information",
  "Free Government Phone Application Online",
  "Free Government Phone Benefits Programs",
  "Free Government Phone Provider Coverage Areas",
  "Free Government Phone Program Service",
  "Free Government Phone Service Registration",
  "Free Government Phone Enrollment Available",
  "Free Government Phone Application Help",
  "Free Government Phone Benefits Service",
  "Free Government Phone Provider Options Nearby",
  "Free Government Phone Program Access Now",
  "Free Government Phone Service Available Now",
  "Free Government Phone Coverage Statewide",
  "Free Government Phone Application Now",
  "Free Government Phone Benefits Available Now",
  "Free Government Phone Provider Network Access",
  "Free Government Phone Program Today",
  "Free Government Phone Service Today",
  "Free Government Phone Enrollment Now"
];

// ============================================================================
// MAIN EXPORT FUNCTION
// ============================================================================

export function getH3Variation(
  domain: string,
  pageType: 'city' | 'state',
  position: number = 0
): string {
  const variations = pageType === 'city' ? CITY_H3S : STATE_H3S;
  
  // Use position as salt for multiple H3s on same page
  return selectVariation(domain, variations, `h3-${pageType}-${position}`);
}




